#!/bin/bash

# 切换到脚本所在目录
cd "$(dirname "${BASH_SOURCE[0]}")"

# 保存脚本所在目录的路径
SCRIPT_DIR="/DockerLNMP"

CONFIG_SCRIPT_PATH="$SCRIPT_DIR/config.sh"
DOCKER_SCRIPT_PATH="$SCRIPT_DIR/docker/docker.sh"
INSTALL_SCRIPT_PATH="$SCRIPT_DIR/install.sh"
MENU_SCRIPT_PATH="$SCRIPT_DIR/menu.sh"
UNINSTALL_SCRIPT_PATH="$SCRIPT_DIR/uninstall.sh"
UPDATE_SCRIPT_PATH="$SCRIPT_DIR/update.sh"

# 其他配置...

# 路径调试信息
# echo "CONFIG_SCRIPT_PATH: $CONFIG_SCRIPT_PATH"
# echo "DOCKER_SCRIPT_PATH: $DOCKER_SCRIPT_PATH"
# echo "INSTALL_SCRIPT_PATH: $INSTALL_SCRIPT_PATH"
# echo "MENU_SCRIPT_PATH: $MENU_SCRIPT_PATH"
# echo "UNINSTALL_SCRIPT_PATH: $UNINSTALL_SCRIPT_PATH"
# echo "UPDATE_SCRIPT_PATH: $UPDATE_SCRIPT_PATH"
