version: "3.8"

services:
  nginx:
    build:
      context: ./nginx/docker-nginx/mainline/debian
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./nginx/vhost/default.conf:/etc/nginx/conf.d/default.conf # 局部配置
      # - ./nginx/certs:/etc/nginx/
      - /var/www/html:/var/www/html
    environment:
      NGINX_VERSION: 1.25.4
      NJS_VERSION: 0.8.3
      PKG_RELEASE: 1~bookworm
    command: [ "nginx", "-g", "daemon off;" ]
    logging:
      driver: "json-file"
      options:
        max-size: "1M"
        max-file: "1"
    depends_on:
      - php
    networks:
      - lnmp-network

  mariadb:
    build:
      context: ./mariadb/docker-mariadb/11.2
      dockerfile: Dockerfile
    environment:
      MARIADB_ROOT_PASSWORD: "${TESTSUITE_PASSWORD:-my-secret-pw}" # my-secret-pw is test
    healthcheck:
      test:
        [
          "CMD",
          "mariadb-admin",
          "ping",
          "-uroot",
          "-p${TESTSUITE_PASSWORD:-my-secret-pw}"
        ]
      start_period: 10s
      interval: 5s
      timeout: 60s
      retries: 10
    logging:
      driver: "json-file"
      options:
        max-size: "1M"
        max-file: "1"
    networks:
      - lnmp-network

  php:
    build:
      context: ./php/docker-php/8.3/alpine3.19/fpm
      dockerfile: Dockerfile
    volumes:
      - /var/www/html:/var/www/html
    logging:
      driver: "json-file"
      options:
        max-size: "1M"
        max-file: "1"
    depends_on:
      - mariadb
      - redis
    networks:
      - lnmp-network

  phpmyadmin:
    build:
      context: ./phpmyadmin/docker-phpmyadmin/apache
      dockerfile: Dockerfile
    environment:
      PMA_HOST: mariadb
      UPLOAD_LIMIT: 123M
      MAX_EXECUTION_TIME: 125
      HIDE_PHP_VERSION: 1
    ports:
      - "8080:80"
    volumes:
      - ../config.user.inc.php:/etc/phpmyadmin/config.user.inc.php:ro
    healthcheck:
      test: [ "CMD", "curl", "-Ss", "http://localhost/robots.txt" ]
      start_period: 5s
      interval: 3s
      timeout: 60s
      retries: 10
    logging:
      driver: "json-file"
      options:
        max-size: "1M"
        max-file: "1"
    networks:
      - lnmp-network
    depends_on:
      - mariadb

  redis:
    build:
      context: ./redis/docker-redis/7.2/debian
      dockerfile: Dockerfile
    logging:
      driver: "json-file"
      options:
        max-size: "1M"
        max-file: "1"
    networks:
      - lnmp-network

networks:
  lnmp-network:
